In [12]:
import pandas as pd

tickers = ['TSLA', 'MSFT', 'GOOGL', 'AAPL']
for ticker in tickers:
    df = pd.read_csv(ticker+'_scores.csv')
    df = df.sort_values(by='Date')
    df.to_csv(ticker+'_scores.csv', index=False)

In [5]:
df.sort_values(by='Date')

          Date Info  Sentiment Score Stock
8   2019-12-09   []         0.414824  TSLA
9   2019-12-10   []         0.414824  TSLA
10  2019-12-11   []         0.414824  TSLA
11  2019-12-12   []         0.414824  TSLA
12  2019-12-13   []         0.414824  TSLA
..         ...  ...              ...   ...
3   2020-12-01   []         0.414824  TSLA
4   2020-12-02   []         0.414824  TSLA
5   2020-12-03   []         0.414824  TSLA
6   2020-12-04   []         0.414824  TSLA
7   2020-12-07   []         0.414824  TSLA

[252 rows x 4 columns]

In [14]:
tickers = ['TSLA', 'MSFT', 'GOOGL', 'AAPL']
for ticker in tickers:
    df = pd.read_csv(ticker+'_scores.csv')
    df = df[['Stock', 'Date', 'Info', 'Sentiment Score']]
    df.to_csv(ticker+'_scores.csv', index=False)

In [82]:
import pandas as pd
import warnings
from pandas.core.common import SettingWithCopyWarning

warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

df = pd.read_csv('stocks.csv')
tickers = ['MSFT', 'TSLA', 'GOOGL', 'AAPL']
stockdata = {}
for ticker in tickers:
    stockdata[ticker] = df.loc[df['Stock'] == ticker]
    stocksent = pd.read_csv(ticker+'_scores.csv')
    stocksent = stocksent[['Stock', 'Date', 'Sentiment Score']]
    stocksent = stocksent.set_index(stockdata[ticker].index)
    stockdata[ticker]['Sentiment Score'] = stocksent['Sentiment Score']
    stockdata[ticker].to_csv(ticker+'_with_sentiment.csv')
stockdata['AAPL']

,Date,Open,High,Low,Close,Adj Close,Volume,Stock,Sentiment Score
252,2019-12-09,67.500000,67.699997,66.227501,66.730003,65.621384,128042400,AAPL,0.414954
253,2019-12-10,67.150002,67.517502,66.464996,67.120003,66.004898,90420400,AAPL,0.414954
254,2019-12-11,67.202499,67.775002,67.125000,67.692497,66.567886,78756800,AAPL,0.414954
255,2019-12-12,66.945000,68.139999,66.830002,67.864998,66.737518,137310400,AAPL,0.414954
256,2019-12-13,67.864998,68.824997,67.732498,68.787498,67.644707,133587600,AAPL,0.414954
...,...,...,...,...,...,...,...,...,...
499,2020-12-01,121.010002,123.470001,120.010002,122.720001,122.720001,128166800,AAPL,0.414954
500,2020-12-02,122.019997,123.370003,120.889999,123.080002,123.080002,89004200,AAPL,0.414954
501,2020-12-03,123.519997,123.779999,122.209999,122.940002,122.940002,78967600,AAPL,0.414954
502,2020-12-04,122.599998,122.860001,121.519997,122.250000,122.250000,78260400,AAPL,0.414954
503,2020-12-07,122.309998,124.570000,122.250000,123.750000,123.750000,86561300,AAPL,0.414954